services:
  - type: web
    name: aramabul-app
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: DB_SSL
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
